### ISSUE TITLE
Reset is using FLUSHALL instead of FLUSHDB

### ISSUE THREAD

**Issue by vpriem** [node-cache-manager/node-cache-manager-ioredis-yet#172]
Hi!

I was wondering if using [FLUSHALL](https://github.com/node-cache-manager/node-cache-manager-ioredis-yet/blob/master/src/index.ts#L122) was a deliberate choice?

This could have dramatic side effect, cause calling `reset()` would flush all databases of the redis instance instead of only the current database the cache store is setup with.

**Comment by botika** [comment]
Well, I don't know how it got there. In `cache-manager-node-redis` it's fine, can you do the PR please?

**Comment by botika** [comment]
thanks! Fixed `1.2.2`
