### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by xts-velkumars** [node-cache-manager/node-cache-manager-ioredis-yet#326]
Good day, 

I'm getting below exception, while creating cache instance. I'm using below packages

**"@angular/animations": "^17.1.0",
"@angular/common": "^17.1.0",
"@angular/compiler": "^17.1.0",
"@angular/core": "^17.1.0",
"@angular/forms": "^17.1.0",
"cache-manager-ioredis-yet": "^1.2.2"**

I'm using below code 

```
  async onLogin() {
    const config: RedisOptions & Config = {  
      host: 'localhost',
      port: 5002,
      ttl: 0,
    };
    const redisCache = await caching(redisStore, config);
  }
```

![image](https://github.com/node-cache-manager/node-cache-manager-ioredis-yet/assets/13570225/2c07b150-d669-47aa-b4bb-50541a23a0ac)

**Comment by jaredwray** [comment]
@xts-velkumars I am not able to duplicate this issue.

**Comment by xts-velkumars** [comment]
@jaredwray, 

I have created sample repository. I can able to reproduce the issue 

https://github.com/xts-velkumars/redis-angular
