### ISSUE TITLE
Report breaking changes in release tag

### ISSUE THREAD

**Issue by matthieuMay** [node-cache-manager/node-cache-manager-ioredis-yet#339]
Version 2.0.0 contains a huge breaking change (https://github.com/node-cache-manager/node-cache-manager-ioredis-yet/commit/3dc547b6f5221956499af7c131c3fe4485351222) that needs to be taken into account before releasing

You probably should add this to 

https://github.com/node-cache-manager/node-cache-manager-ioredis-yet/releases/tag/2.0.0

**Comment by jaredwray** [comment]
@matthieuMay we did a fix on this with v2.0.2. Let us know if that solved it.

**Comment by jaredwray** [comment]
@matthieuMay - ah gotcha and we will take that into consideration moving forward.
