### ISSUE TITLE
Feature Request: Silently ignore noncacheable values instead of throwing error

### ISSUE THREAD

**Issue by edosrecki** [node-cache-manager/node-cache-manager-ioredis-yet#46]
Hello!

I have a following feature request, and would like to know your opinion about it. I am willing to submit a PR if you agree with the proposal.

Currently, `set` and `mset` functions throw an error if a provided value is noncacheable. I would like to propose adding a boolean configuration option to choose whether to throw an error, or simply ignore the noncacheable value(s) and proceed:

Example:
```ts
const cache = await caching(redisStore, { throwNoncacheable: false /* default: true */ });

// set
await cache.set('foo', null); // does not throw
assert.equal(
  await cache.get('foo'),
  undefined
);

// mset
await cache.mset([
  ['foo', null],
  ['bar', 1]
]); // does not throw

assert.deepStrictEqual(
  await cache.mget('foo', 'bar'),
  [undefined, 1]
);
```

**Comment by botika** [comment]
Do you like this solution? Wait for your comments. If you like, you could also implement it in the redis version. And the tests on a cluster are missing in case you have a while.
